[project]
name = "mirai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.79.0",
    "fastapi>=0.128.7",
    "uvicorn>=0.40.0",
]
